language: php

branches:
  only:
    - 6.x-and-above
php:
  - 5.6
  - 7.4
  - 8.1
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: vendor/bin/codecept run
